apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spa-demo
  namespace: spa-demo
  labels:
    app: spa-demo
    deployment: spa-demo-deployment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-demo
  template:
    metadata:
      labels:
        app: spa-demo
        deployment: spa-demo-deployment
    spec:
      containers:
        - name: spa-demo
          image: ${HARBOR_HOST}/library/malston/spa-demo:v1
          ports:
          - containerPort: 80
