apiVersion: v1
kind: Service
metadata:
  name: spa-demo-loadbalancer
  namespace: spa-demo
  labels:
    deployment: spa-demo-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: spa-demo
    deployment: spa-demo-deployment
