apiVersion: v1
kind: Service
metadata:
  name: spa-demo
  namespace: spa-demo
  labels:
    app: spa-demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: spa-demo
